//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDiseasePrediction
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeartDiseaseTrainingSet
    {
        public int IdPatient { get; set; }
        public int Age { get; set; }
        public int IsWoman { get; set; }
        public int IdChestPainType { get; set; }
        public int RestingBloodPreasure { get; set; }
        public int cholestoral { get; set; }
        public int FastingBloodSugar { get; set; }
        public int RestingElectrocardiographicResults { get; set; }
        public int MaxHeartRateAchived { get; set; }
        public int ExcerciseInducedAngina { get; set; }
        public double Oldpeak { get; set; }
        public int Slope { get; set; }
        public int NumberOfMajorVessels { get; set; }
        public int Thal { get; set; }
        public int Target { get; set; }
    }
}
